add delivery service
ryasenchuk/delivery_service pull request #1
Opened 2021-08-20 19:18 UTC by ryasenchuk

2021-08-23 10:48 UTC, averevkin requested changes

2021-08-23 10:48 UTC, averevkin commented on bike.rb
> +
Не надо так много лишних пробелов. Пустыми строками мы разделяем логические части кода(блок инклудов, ацессоров, методов и т.д.)

2021-08-23 10:48 UTC, averevkin commented on deliveryservice.rb
> +    @bikes = Array.new(bikes) {Bike.new}
Добавте пробелы после и перед фигурными скобками

2021-08-23 10:48 UTC, averevkin commented on transport.rb
> +    speed_with_kg <=> other.speed_with_kg
Это не ошибка, но в задании хотелось бы видеть решение без использования <=>, для понимания как работет этот опратор.

2021-08-23 10:48 UTC, averevkin commented on transport.rb
> +    @max_weight = max_weight
Т.к. max_weight является знаменателем в ваших вычислениях, то при инициализации объекта лучше сделать проверку на 0 в отдельном методе

2021-08-23 10:48 UTC, averevkin commented on deliveryservice.rb
> +  def initialize(cars, bikes)
Лучше назвать cars_number, bikes_number, а то названия слегка конфьюзят

2021-08-23 10:48 UTC, averevkin commented on deliveryservice.rb
> +        if a.available == true
1) Однострочные if лучше писать как postfix. 
2) Сравнение чего то с true - избыточно, достаточно отталкиваться от значения a.available

Этот each уже реализован тут:
https://ruby-doc.org/core-2.6.7/Enumerable.html#method-i-select

2021-08-23 10:48 UTC, averevkin commented on deliveryservice.rb
> +  def find_transport( package_weight, package_distance)
Если этот метод будет возвращать nil ничего страшного, это валидно

2021-08-23 10:48 UTC, averevkin commented on deliveryservice.rb
> +      'Available transport not found'
Не стоит тут возвращать String. Рекомендуется возвращать объекты которые сходны по duck type или же nil

2021-08-24 08:54 UTC, ryasenchuk commented on transport.rb
> +    @max_weight = max_weight
Подскажите, а если значение max_weight  передается через константу, все равно его нужно проверять?
Спасибо.

2021-08-25 09:46 UTC, averevkin commented
Проверил. Не все пункты ревью были исправлены

2021-08-25 09:46 UTC, merged