add new method and optimization deliveryservice
ryasenchuk/delivery_service pull request #2
Opened 2021-08-31 18:39 UTC by ryasenchuk

2021-09-02 08:50 UTC, averevkin requested changes

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +
Достаточно разделять одной новой строкой

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +  describe '.new' do
Тут вы проверяете конструктор руби объекта. Такие вещи не тестируются т.к. это функционал языка

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +  describe '#available' do
Вот как раз тесты на начальный стейт могуть быть включены в тест для new, т.е.
describe '.new' do
  it 'creates available Bike'
  it 'creates Bike with max_distance'
  it 'creates Bike with speed'
end

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +      allow(bike).to receive(:delivery_time).with(distance).and_return(result)
Тут мок не нужен, т.к. вы здесь подменяете логику своего реального метода на мок. Получается ваш тест кейс тестит мок данных а не реальный ответ delivery_time. Если вдруг реализация этого метода поменяется тест будет всё равно зелёный

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +
не нужная пустая строка

2021-09-02 08:50 UTC, averevkin commented on Spec/bike_spec.rb
> +    it do
Каждый it должен иметь description что он тестит

2021-09-02 08:50 UTC, averevkin commented on Spec/car_spec.rb
> +require 'rspec'
Все коменты касательно bike_spec актуальны и для этого файла

2021-09-02 08:50 UTC, averevkin commented on Spec/deliveryservice_spec.rb
> +
Нет тестов для методов verification_cars и find_transport

2021-09-02 08:50 UTC, averevkin commented on Spec/deliveryservice_spec.rb
> +require_relative '../deliveryservice.rb'
Файлы в Ruby именуются через snake_case delivery_service.rb

2021-09-02 08:50 UTC, averevkin commented on deliveryservice.rb
Зачем чтолько пустых строк?

2021-09-02 08:50 UTC, averevkin commented on deliveryservice.rb
> +    available_cars = cars_number.select { |a| a.available == true }
Сравнение с true не нужно

2021-09-02 08:50 UTC, averevkin commented on deliveryservice.rb
> +    @cars_number = Array.new(Constants::CAR[:count]) { Car.new }
Надо объеденить эти 2 массива в 1

2021-09-02 08:50 UTC, averevkin commented on deliveryservice.rb
>    def find_transport( package_weight, package_distance)
В задании требовалось избавиться от условных операторов

2021-09-02 08:50 UTC, averevkin commented on transport.rb
>    def speed_with_kg
Старайтесь не использовать единицы измерения в нейминге, т.к. они могут быть разные

2021-09-02 08:50 UTC, averevkin commented on transport.rb
> +  def comparison_max_w
Не используйте однобуквенные сокращения т.к. не понятно что w значит

2021-09-02 08:50 UTC, averevkin commented on transport.rb
> +    @max_distance || Float::INFINITY
@max_distance атрибут имеет только Bike.

2021-09-02 08:50 UTC, averevkin commented on transport.rb
> +  def comparison_max_d
нет смысла определять этот метод. Вы должны в <=> проверить отвечает ли транспорт на max_distance и если нет использовать Float::INFINITY. В данной реализации сложно просмотрев только код метода <=> понять что и как он сравнивает

2021-09-04 17:20 UTC, ryasenchuk commented on Spec/bike_spec.rb
> +  describe '#available' do
С тестами пока не до конца разобрался, поэтому не добавил еще. Остальные замечания постарался исправить.

2021-09-06 09:20 UTC, averevkin commented
Заканчивате тесты и можете мержить этот пул реквест

2021-09-09 15:49 UTC, merged